In [5]:
import numpy as np

a = np.matrix([[1, 2], [3, 4]])
b = np.matrix([[1, 2], [3, 4]])
print(a.dot(b))
print(a *b)

a = np.matrix([[1, 1],[1, 0]])
print(a.T)

[[ 7 10]
 [15 22]]
[[ 7 10]
 [15 22]]
[[ 0.  1.]
 [ 1. -1.]]
